export const ENDPOINTS = {
  CATEGORIES: 'categories',
  REGISTER: 'register',
  LOGIN: 'login',
  LOGOUT: 'logout',
  USERS: 'admin/users',
  PENDING_USERS: 'admin/pending-users',
  ACCEPTED_USERS: 'admin/accepted-users',
  ADD_USER: 'admin/create-user',
  DELETE_USER: 'admin/delete-user-account',
  VALIDATE_USER: 'admin/validate-user-account',
  REJECT_USER: 'admin/reject-user-account',
  SUSPEND_USER: 'admin/suspend-account',
  EDIT_USER: 'admin/update-user-account',
  SET_PASSWORD: 'password-set/?token=',
  SEND_RESET_PASSWORD_EMAIL: 'send-password-reset-mail',
  USER_PROFILE: 'profile',
  UPDATE_PROFILE: 'update-profile',
  DELETE_CATEGORY: 'admin/delete-category',
  CREATE_CATEGORY: 'admin/create-category',
  UPDATE_CATEGORY: 'admin/update-category',
  REFRESH_TOKEN: 'refresh-token',
}
